import { Product, Category, Order, Vendor, Customer } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'الكل', icon: 'LayoutGrid' },
  { id: 'electronics', name: 'إلكترونيات', icon: 'Smartphone' },
  { id: 'mobiles', name: 'موبايلات', icon: 'Smartphone', parentId: 'electronics' },
  { id: 'tvs', name: 'تلفزيونات', icon: 'Tv', parentId: 'electronics' },
  { id: 'computer_world', name: 'عالم الكمبيوتر', icon: 'Cpu', parentId: 'electronics' },
  { id: 'headphones', name: 'سماعات', icon: 'Headphones', parentId: 'electronics' },
  { id: 'smartwatches', name: 'ساعات ذكية', icon: 'Watch', parentId: 'electronics' },
  { id: 'laptops', name: 'لابتوب', icon: 'Laptop', parentId: 'electronics' },
  { id: 'speakers', name: 'سبيكر', icon: 'Speaker', parentId: 'electronics' },
  { id: 'mobile_accessories', name: 'اكسسوارات موبايل', icon: 'Cable', parentId: 'electronics' },
  { id: 'printer_supplies', name: 'مستلزمات طابعة', icon: 'Printer', parentId: 'electronics' },
  { id: 'cameras', name: 'كاميرات', icon: 'Camera', parentId: 'electronics' },
  { id: 'fashion', name: 'أزياء', icon: 'Shirt' },
  { id: 'men', name: 'رجالي', icon: 'User', parentId: 'fashion' },
  { id: 'women', name: 'نسائي', icon: 'User', parentId: 'fashion' },
  { id: 'girls', name: 'بناتي', icon: 'Baby', parentId: 'fashion' },
  { id: 'boys', name: 'ولادي', icon: 'Baby', parentId: 'fashion' },
  { id: 'kids', name: 'الأطفال', icon: 'Baby', parentId: 'fashion' },
  { id: 'travel_essentials', name: 'مستلزمات السفر', icon: 'Briefcase', parentId: 'fashion' },
  { id: 'shoes', name: 'الأحذية', icon: 'Footprints', parentId: 'fashion' },
  { id: 'watches_fashion', name: 'الساعات', icon: 'Watch', parentId: 'fashion' },
  { id: 'sportswear', name: 'ملابس رياضية', icon: 'Dumbbell', parentId: 'fashion' },
  { id: 'home', name: 'المنزل', icon: 'Home' },
  { id: 'cleaning_tools', name: 'أدوات التنظيف', icon: 'BrushCleaning', parentId: 'home' },
  { id: 'bedding', name: 'الفراش', icon: 'Bed', parentId: 'home' },
  { id: 'storage_organization', name: 'التخزين والتنظيم', icon: 'Archive', parentId: 'home' },
  { id: 'furniture', name: 'الأثاث', icon: 'Sofa', parentId: 'home' },
  { id: 'home_appliances', name: 'الأجهزة المنزلية', icon: 'Microwave', parentId: 'home' },
  { id: 'waste_recycling', name: 'النفايات وإعادة التدوير', icon: 'Recycle', parentId: 'home' },
  { id: 'home_decor', name: 'ديكور المنزل', icon: 'Palette', parentId: 'home' },
  { id: 'beepharma', name: 'BeePharma', icon: 'Bug' },
  { id: 'honey', name: 'عسل', icon: 'Droplets', parentId: 'beepharma' },
  { id: 'creams', name: 'كريمات', icon: 'Sparkles', parentId: 'beepharma' },
  { id: 'herbs', name: 'أعشاب', icon: 'Leaf', parentId: 'beepharma' },
  { id: 'shampoos', name: 'شامبوهات', icon: 'Bath', parentId: 'beepharma' },
  { id: 'incense', name: 'بخور', icon: 'Wind', parentId: 'beepharma' },
  { id: 'natural_soap', name: 'صابون طبيعي', icon: 'Square', parentId: 'beepharma' },
  { id: 'therapeutic_mixtures', name: 'خلطات علاجية', icon: 'FlaskConical', parentId: 'beepharma' },
  { id: 'beauty', name: 'الجمال', icon: 'Sparkles' },
  { id: 'skin_care', name: 'العناية بالبشرة', icon: 'Sparkles', parentId: 'beauty' },
  { id: 'makeup', name: 'المكياج', icon: 'Palette', parentId: 'beauty' },
  { id: 'hair_care', name: 'العناية بالشعر', icon: 'Scissors', parentId: 'beauty' },
  { id: 'mens_perfumes', name: 'عطور رجالية', icon: 'Flame', parentId: 'beauty' },
  { id: 'womens_perfumes', name: 'عطور نسائية', icon: 'Flame', parentId: 'beauty' },
  { id: 'mens_care', name: 'العناية بالرجال', icon: 'User', parentId: 'beauty' },
  { id: 'seasonal_products', name: 'منتجات موسمية', icon: 'Sun', parentId: 'beauty' },
  { id: 'beauty_devices', name: 'أجهزة الجمال', icon: 'Zap', parentId: 'beauty' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'ساعة ذكية برو',
    description: 'ساعة ذكية متطورة مع تتبع الصحة والأنشطة الرياضية وشاشة AMOLED.',
    price: 299,
    quantity: 15,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 124
  },
  {
    id: '2',
    name: 'سماعات لاسلكية',
    description: 'سماعات بلوتوث مع خاصية إلغاء الضجيج وبطارية تدوم طويلاً.',
    price: 150,
    quantity: 20,
    category: 'headphones',
    image: 'https://picsum.photos/seed/earbuds/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 89
  },
  {
    id: '7',
    name: 'جهاز لابتوب ألترا',
    description: 'لابتوب فائق النحافة مع معالج قوي وشاشة 4K للعمل الإبداعي والألعاب.',
    price: 1299,
    quantity: 8,
    category: 'laptops',
    image: 'https://picsum.photos/seed/laptop/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 32
  },
  {
    id: '8',
    name: 'نظام مسرح منزلي فاخر',
    description: 'تجربة سينمائية متكاملة في منزلك مع صوت محيطي 7.1 وتقنية لاسلكية.',
    price: 2499,
    quantity: 3,
    category: 'tvs',
    image: 'https://picsum.photos/seed/theater/400/400',
    images: [],
    rating: 5.0,
    reviewsCount: 12
  },
  {
    id: 'elec-new-1',
    name: 'هاتف آيفون 15 برو ماكس',
    description: 'أحدث هاتف ذكي من آبل بكاميرا احترافية وشريحة A17 Pro الفائقة السرعة.',
    price: 4800,
    quantity: 12,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/iphone/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 340
  },
  {
    id: 'elec-new-2',
    name: 'لوحة مفاتيح ميكانيكية مضيئة',
    description: 'لوحة مفاتيح ميكانيكية مخصصة للألعاب مع إضاءة RGB ومفاتيح سريعة الاستجابة.',
    price: 180,
    quantity: 25,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/keyboard/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 112
  },
  {
    id: '3',
    name: 'قميص قطني عصري',
    description: 'قميص مريح مصنوع من القطن الطبيعي 100% بتصميم كلاسيكي.',
    price: 45,
    quantity: 50,
    category: 'men',
    image: 'https://picsum.photos/seed/shirt/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 56
  },
  {
    id: '4',
    name: 'حقيبة ظهر جلدية',
    description: 'حقيبة ظهر أنيقة ومتينة مناسبة للعمل والسفر.',
    price: 85,
    quantity: 10,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/backpack/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 34
  },
  {
    id: 'fash-new-1',
    name: 'فستان سهرة مخملي أنيق',
    description: 'فستان نسائي فاخر من المخمل الناعم مناسب للحفلات والمناسبات السعيدة.',
    price: 250,
    quantity: 18,
    category: 'women',
    image: 'https://picsum.photos/seed/dress/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 74
  },
  {
    id: 'fash-new-2',
    name: 'حذاء رياضي مريح للجري',
    description: 'حذاء مخصص للركض والتمارين الرياضية بنعل طبي ممتص للصدمات ووزن خفيف جداً.',
    price: 140,
    quantity: 30,
    category: 'shoes',
    image: 'https://picsum.photos/seed/runningshoes/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 156
  },
  {
    id: 'fash-new-3',
    name: 'طقم بدلة رسمية فاخرة',
    description: 'بدلة رجالية كلاسيكية بتصميم عصري وألوان مميزة تلائم الاجتماعات والمناسبات الرسمية.',
    price: 499,
    quantity: 8,
    category: 'men',
    image: 'https://picsum.photos/seed/suit/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 38
  },
  {
    id: 'fash-new-4',
    name: 'ساعة يد كلاسيكية جلدية',
    description: 'ساعة يد فاخرة بسير من الجلد الطبيعي المقاوم للاهتراء وهيكل فولاذي مقاوم للماء.',
    price: 180,
    quantity: 15,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/classicwatch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 65
  },
  {
    id: '5',
    name: 'ماكينة قهوة أوتوماتيكية',
    description: 'استمتع بأفضل كوب قهوة في منزلك مع هذه الماكينة سهلة الاستخدام.',
    price: 450,
    quantity: 5,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/coffee/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 210
  },
  {
    id: 'home-new-1',
    name: 'طقم غطاء سرير قطني ناعم',
    description: 'طقم سرير مزدوج مصنوع من القطن المصري الفاخر بنسبة 100% لنوم هادئ ومريح.',
    price: 110,
    quantity: 20,
    category: 'bedding',
    image: 'https://picsum.photos/seed/bedding/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 88
  },
  {
    id: 'home-new-2',
    name: 'مكنسة روبوتية ذكية',
    description: 'مكنسة ذكية تعمل ذاتياً مع ميزة التوجيه بالليزر والتنظيف الرطب ومستشعر العقبات.',
    price: 380,
    quantity: 14,
    category: 'cleaning_tools',
    image: 'https://picsum.photos/seed/robotvacuum/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 114
  },
  {
    id: 'home-new-3',
    name: 'مجموعة منظمات زجاجية',
    description: 'طقم من 6 مرطبانات زجاجية متينة مع أغطية خشبية محكمة لحفظ البهارات والمكونات.',
    price: 65,
    quantity: 45,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/jars/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 42
  },
  {
    id: 'home-new-4',
    name: 'أريكة استرخاء مخملية',
    description: 'كرسي أريكة مفرد مريح للغاية ومبطن بطبقات كثيفة من الإسفنج مع قماش مخملي ناعم.',
    price: 1200,
    quantity: 5,
    category: 'furniture',
    image: 'https://picsum.photos/seed/chair/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 23
  },
  {
    id: 'home-new-5',
    name: 'مصباح أرضي ذكي RGB',
    description: 'مصباح أرضي أنيق بتصميم عصري يمنحك ملايين الألوان مع إمكانية التحكم عبر الهاتف.',
    price: 49,
    quantity: 50,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/lamp/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 61
  },
  {
    id: 'bee-1',
    name: 'عسل النحل الطبيعي - BeePharma',
    description: 'عسل نحل طبيعي 100% غني بالفيتامينات والمعادن لتعزيز المناعة.',
    price: 45,
    quantity: 100,
    category: 'honey',
    image: 'https://picsum.photos/seed/honey/400/400',
    images: [],
    rating: 5.0,
    reviewsCount: 150
  },
  {
    id: 'bee-2',
    name: 'كريم مرطب طبيعي',
    description: 'كريم غني بزبدة الشيا والزيوت الطبيعية لترطيب عميق.',
    price: 35,
    quantity: 50,
    category: 'creams',
    image: 'https://picsum.photos/seed/cream/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 42
  },
  {
    id: 'bee-3',
    name: 'مجموعة أعشاب مهدئة',
    description: 'مزيج من الأعشاب الطبيعية للمساعدة على الاسترخاء والنوم الهادئ.',
    price: 25,
    quantity: 80,
    category: 'herbs',
    image: 'https://picsum.photos/seed/herbs/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 65
  },
  {
    id: 'bee-4',
    name: 'بخور عود فاخر',
    description: 'بخور عود طبيعي برائحة زكية تدوم طويلاً.',
    price: 60,
    quantity: 30,
    category: 'incense',
    image: 'https://picsum.photos/seed/incense/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 88
  },
  {
    id: 'bee-5',
    name: 'صابون زيت الزيتون الطبيعي',
    description: 'صابون مصنوع يدوياً من زيت الزيتون النقي للبشرة الحساسة.',
    price: 15,
    quantity: 120,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/soap/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 54
  },
  {
    id: 'bee-6',
    name: 'خلطة العسل والبروبوليس الفائقة',
    description: 'خلطة علاجية طبيعية تجمع عسل السدر الجبلي والغذاء الملكي والبروبوليس لتقوية المناعة ومحاربة السموم.',
    price: 95,
    quantity: 240,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/propolis/400/400',
    images: [],
    rating: 5.0,
    reviewsCount: 240
  },
  {
    id: '6',
    name: 'مجموعة العناية بالبشرة',
    description: 'مجموعة متكاملة لترطيب وتغذية البشرة بمكونات طبيعية.',
    price: 120,
    quantity: 30,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/skincare/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 45
  },
  {
    id: 'beauty-sub-1',
    name: 'أحمر شفاه كلاسيكي مطفأ',
    description: 'أحمر شفاه كريمي باللون الأحمر الكلاسيكي وثبات يدوم طويلاً دون جفاف.',
    price: 25,
    quantity: 40,
    category: 'makeup',
    image: 'https://picsum.photos/seed/lipstick/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 82
  },
  {
    id: 'beauty-sub-2',
    name: 'سيروم مغذي للشعر بالأرغان',
    description: 'سيروم طبيعي يعيد اللمعان والقوة للشعر التالف ويمنع التقصف.',
    price: 39,
    quantity: 25,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/haircare/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 95
  },
  {
    id: 'beauty-sub-3',
    name: 'عطر فرنسي فاخر - لافي',
    description: 'عطر فرنسي كلاسيكي بمزيج من أزهار الياسمين والخشب الأبيض والمسك.',
    price: 110,
    quantity: 15,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/perfume/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 150
  },
  {
    id: 'beauty-sub-5',
    name: 'عطر بلو شانيل المثير للرجال',
    description: 'عطر رجالي منعش وفواح بملاحظات الحمضيات والأخشاب الدافئة والعود الخفيف.',
    price: 125,
    quantity: 20,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/mensperfume/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 210
  },
  {
    id: 'beauty-sub-4',
    name: 'جهاز تنظيف البشرة بالموجات',
    description: 'جهاز متطور لتنظيف وإزالة الرؤوس السوداء والشوائب بلطف وتقشير الخلايا.',
    price: 75,
    quantity: 12,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/beautydevice/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 28
  },
  // --- 8 NEW PRODUCTS FOR ELECTRONICS ---
  {
    id: 'elec-new-3',
    name: 'مكبر صوت بلوتوث مقاوم للماء',
    description: 'سبيكر لاسلكي محمول مع صوت نقي وعميق ومقاومة ممتازة للماء والغبار.',
    price: 120,
    quantity: 35,
    category: 'speakers',
    image: 'https://picsum.photos/seed/waterproofspeaker/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 45
  },
  {
    id: 'elec-new-4',
    name: 'كاميرا احترافية بدقة 4K',
    description: 'كاميرا بدون مرآة بعدسة متطورة لالتقاط أجمل اللحظات بدقة فائقة الجودة.',
    price: 1850,
    quantity: 10,
    category: 'cameras',
    image: 'https://picsum.photos/seed/dslrcamera/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 29
  },
  {
    id: 'elec-new-5',
    name: 'شاحن لاسلكي سريع ثلاثي في واحد',
    description: 'شاحن لاسلكي مغناطيسي سريع لشحن الآيفون، الساعة الذكية، وسماعات الأذن في نفس الوقت وبقوة 15 واط.',
    price: 75,
    quantity: 40,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/chargingdock/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 88
  },
  {
    id: 'elec-new-6',
    name: 'طابعة صور ذكية لاسلكية',
    description: 'طابعة صور جيب صغيرة وسهلة الاستخدام لطباعة اللحظات الجميلة فوراً من جوالك بجودة عالية وبدون حبر.',
    price: 140,
    quantity: 15,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/photo-printer/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 34
  },
  {
    id: 'elec-new-7',
    name: 'شاشة ألعاب منحنية 165Hz',
    description: 'شاشة ألعاب متطورة مقاس 27 بوصة مع معدل تحديث فائق السرعة واستجابة 1ms لتجربة لعب مثالية وسلسة.',
    price: 320,
    quantity: 8,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/gamingmonitor/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 52
  },
  {
    id: 'elec-new-8',
    name: 'سماعة رأس لاسلكية مخصصة للألعاب',
    description: 'سماعة ألعاب محيطية 7.1 مع ميكروفون عازل للضوضاء وتصميم مريح لساعات طويلة من اللعب المتواصل.',
    price: 99,
    quantity: 22,
    category: 'headphones',
    image: 'https://picsum.photos/seed/gamingheadset/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 65
  },
  {
    id: 'elec-new-9',
    name: 'هاتف ذكي أندرويد رائد',
    description: 'هاتف ذكي رائد بشاشة 120Hz وكاميرا بدقة 200 ميجابكسل مع أداء جبار وبطارية تدوم طويلاً.',
    price: 1100,
    quantity: 12,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/androidphone/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 94
  },
  {
    id: 'elec-new-10',
    name: 'ساعة رياضية ذكية متينة',
    description: 'ساعة ذكية مخصصة للرياضات القاسية والمغامرات مع تتبع دقيق لنظام تحديد المواقع وعمر بطارية فائق يصل لـ 14 يوماً.',
    price: 249,
    quantity: 15,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/ruggedwatch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 41
  },

  // --- 8 NEW PRODUCTS FOR FASHION ---
  {
    id: 'fash-new-5',
    name: 'سترة رياضية مقاومة للرياح',
    description: 'سترة رياضية خفيفة الوزن ومقاومة للماء والرياح لجميع الأنشطة الخارجية والتمارين الجري.',
    price: 110,
    quantity: 30,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/windbreaker/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 62
  },
  {
    id: 'fash-new-6',
    name: 'فستان بناتي بنقشة الزهور',
    description: 'فستان بناتي رقيق وصيفي مصنوع من القطن الناعم المريح بنقشات صيفية زاهية الألوان.',
    price: 65,
    quantity: 25,
    category: 'girls',
    image: 'https://picsum.photos/seed/girldress/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 41
  },
  {
    id: 'fash-new-7',
    name: 'جاكيت رجالي جينز كلاسيكي',
    description: 'جاكيت جينز متين وتصميم عصري يناسب الإطلالات الكاجوال اليومية والطقس المعتدل.',
    price: 75,
    quantity: 20,
    category: 'men',
    image: 'https://picsum.photos/seed/denimjacket/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 38
  },
  {
    id: 'fash-new-8',
    name: 'حقيبة سفر كلاسيكية بعجلات',
    description: 'حقيبة سفر متينة ومقاومة للصدمات مع عجلات دوارة سلسة ومساحة تخزين واسعة ومنظمة لرحلاتك.',
    price: 160,
    quantity: 12,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/suitcase/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 54
  },
  {
    id: 'fash-new-9',
    name: 'حذاء جلدي رسمي فاخر',
    description: 'حذاء رسمي رجالي مصنوع من الجلد الطبيعي الإيطالي عالي الجودة بتصميم كلاسيكي أنيق للاجتماعات والمناسبات.',
    price: 195,
    quantity: 15,
    category: 'shoes',
    image: 'https://picsum.photos/seed/oxfordshoes/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 29
  },
  {
    id: 'fash-new-10',
    name: 'تي شيرت رياضي سريع الجفاف',
    description: 'تي شيرت رياضي مصنوع من ألياف دقيقة قابلة للتنفس وتطرد الرطوبة للحفاظ على انتعاشك أثناء التمارين.',
    price: 35,
    quantity: 50,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/sporttshirt/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 74
  },
  {
    id: 'fash-new-11',
    name: 'نظارة شمسية كلاسيكية مستقطبة',
    description: 'نظارة شمسية أنيقة بعدسات مستقطبة ومقاومة للخدش لحماية مثالية للعين ورؤية واضحة تحت أشعة الشمس العالية.',
    price: 120,
    quantity: 18,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/sunglasses/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 47
  },
  {
    id: 'fash-new-12',
    name: 'ساعة يد نسائية ذهبية راقية',
    description: 'ساعة يد نسائية فاخرة مطلية بالذهب الوردي ومرصعة ببلورات براقة تمنحك إطلالة ساحرة في المناسبات السعيدة.',
    price: 290,
    quantity: 10,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/luxurywomenwatch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 33
  },

  // --- 8 NEW PRODUCTS FOR HOME ---
  {
    id: 'home-new-6',
    name: 'قلاية هوائية ذكية بدون زيت',
    description: 'قلاية صحية بسعة كبيرة وشاشة لمس رقمية لتحضير أشهى المأكولات بدهون أقل بنسبة 85%.',
    price: 299,
    quantity: 14,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/airfryer/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 142
  },
  {
    id: 'home-new-7',
    name: 'سلة مهملات ذكية بمستشعر حركة',
    description: 'سلة مهملات أنيقة تفتح وتغلق تلقائياً بمستشعر دقيق للحفاظ على النظافة التامة والحد من الروائح.',
    price: 75,
    quantity: 22,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/smartbin/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 38
  },
  {
    id: 'home-new-8',
    name: 'طقم أواني طهي سيراميك صحي',
    description: 'طقم أواني طهي مكون من 10 قطع غير لاصقة وخالية من الرصاص والمواد الكيميائية الضارة لنظام حياة صحي وآمن.',
    price: 240,
    quantity: 10,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/cookware/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 56
  },
  {
    id: 'home-new-9',
    name: 'مرطب وموزع روائح ذكي',
    description: 'مرطب هواء فائق الهدوء وموزع للزيوت العطرية مع إضاءة ليلية دافئة وهادئة لغرفة النوم والمكتب.',
    price: 39,
    quantity: 40,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/diffuser/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 81
  },
  {
    id: 'home-new-10',
    name: 'طقم وسائد طبية مريحة',
    description: 'طقم من وسادتين مصنوعتين من رغوة الذاكرة المرنة لدعم الرقبة والعمود الفقري ومساعدة النوم بعمق وراحة.',
    price: 55,
    quantity: 30,
    category: 'bedding',
    image: 'https://picsum.photos/seed/medicalpillow/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 92
  },
  {
    id: 'home-new-11',
    name: 'مروحة برجية ذكية هادئة',
    description: 'مروحة عمودية هادئة وبدون شفرات مع ميزة تبريد الهواء وتأرجح واسع لتدفق هواء مثالي في الصيف.',
    price: 125,
    quantity: 18,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/towerfan/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 49
  },
  {
    id: 'home-new-12',
    name: 'طقم منظمات أدراج المطبخ',
    description: 'منظم أدراج من خشب البامبو الطبيعي القابل للتوسيع لترتيب الملاعق والسكاكين وأدوات الطهي بكفاءة وأناقة.',
    price: 32,
    quantity: 35,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/drawerorganizer/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 64
  },
  {
    id: 'home-new-13',
    name: 'سجادة أرضية ناعمة كلاسيكية',
    description: 'سجادة أرضية وثيرة وفائقة النعومة بتصميم بوهيمي راقٍ يضفي لمسة جمالية دافئة على غرفة المعيشة والصالات.',
    price: 180,
    quantity: 8,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/bohorug/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 27
  },

  // --- 8 NEW PRODUCTS FOR BEEPHARMA ---
  {
    id: 'bee-7',
    name: 'شامبو القطران الطبيعي لعلاج القشرة',
    description: 'تركيبة عشبية فريدة غنية بالقطران والمستخلصات الطبية لتهدئة فروة الرأس والتخلص النهائي من القشرة والحكة.',
    price: 28,
    quantity: 92,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/tarshampoo/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 92
  },
  {
    id: 'bee-8',
    name: 'عسل السدر مع الغذاء الملكي وحبوب اللقاح',
    description: 'تركيبة طاقة وحيوية طبيعية ممتازة للرياضيين والراغبين بزيادة النشاط البدني والتركيز الذهني والمناعة.',
    price: 115,
    quantity: 180,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/royalhoneyblend/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 180
  },
  {
    id: 'bee-9',
    name: 'كريم شمع النحل لترطيب اليدين والقدمين',
    description: 'مرهم شمع النحل الطبيعي مع زيت اللوز النقي لإصلاح تشققات الجلد وجفاف البشرة الشديد بفعالية فائقة وسريعة.',
    price: 24,
    quantity: 120,
    category: 'creams',
    image: 'https://picsum.photos/seed/beeswaxcream/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 73
  },
  {
    id: 'bee-10',
    name: 'كبسولات عكبر النحل (البروبوليس) الطبيعية',
    description: 'مكمل غذائي طبيعي من عكبر النحل النقي لتقوية المناعة ومقاومة الالتهابات والفيروسات ونزلات البرد اليومية.',
    price: 49,
    quantity: 90,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/propoliscapsules/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 104
  },
  {
    id: 'bee-11',
    name: 'شامبو عسل السدر الطبيعي المغذي',
    description: 'شامبو طبيعي خفيف غني بعسل السدر الطبيعي لترطيب الشعر الجاف والتالف من الجذور بعمق وإعادة لمعانه الطبيعي.',
    price: 22,
    quantity: 110,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/honeyshampoo/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 88
  },
  {
    id: 'bee-12',
    name: 'صابونة عسل النحل والجلسرين الطبيعي',
    description: 'صابونة لطيفة ومرطبة مصنوعة من عسل النحل النقي والجلسرين لتنظيف البشرة الحساسة بعمق وبدون التسبب في جفافها.',
    price: 12,
    quantity: 150,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/honeysoap/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 62
  },
  {
    id: 'bee-13',
    name: 'بخور اللبان الذكر واللافندر المهدئ',
    description: 'مزيج فاخر ومميز من بخور اللبان الذكر العماني واللافندر لتطهير هواء المنزل وتهدئة الأعصاب وإشاعة الاسترخاء.',
    price: 35,
    quantity: 60,
    category: 'incense',
    image: 'https://picsum.photos/seed/frankincense/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 45
  },
  {
    id: 'bee-14',
    name: 'شاي الأعشاب المهدئ للمعدة والقولون',
    description: 'مزيج طبيعي 100% من أزهار البابونج وأوراق النعناع واليانسون لتهدئة الجهاز الهضمي والمساعدة على النوم الهانئ.',
    price: 18,
    quantity: 200,
    category: 'herbs',
    image: 'https://picsum.photos/seed/herbaltea/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 115
  },

  // --- 8 NEW PRODUCTS FOR BEAUTY ---
  {
    id: 'beauty-new-6',
    name: 'رغوة حلاقة وغسول عناية للرجال',
    description: 'مستحضر ثنائي المفعول ينظف البشرة بعمق ويهيئها لعملية حلاقة ناعمة ومثالية للرجال دون تهيج أو جروح.',
    price: 22,
    quantity: 57,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/menshavingshave/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 57
  },
  {
    id: 'beauty-new-7',
    name: 'واقي شمس فيزيائي مقاوم للماء',
    description: 'حماية فائقة من الأشعة فوق البنفسجية الضارة UVA/UVB مع ترطيب خفيف وسريع الامتصاص يدوم طوال اليوم.',
    price: 45,
    quantity: 130,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/sunscreen/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 130
  },
  {
    id: 'beauty-new-8',
    name: 'مكواة تصفيف الشعر الاحترافية بالبلوتونيوم',
    description: 'مكواة شعر سيراميك متطورة لحماية خصلات الشعر من التلف الحراري وفرد وتصفيف الشعر بسلاسة وبسرعة فائقة.',
    price: 150,
    quantity: 20,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/hairstraightener/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 44
  },
  {
    id: 'beauty-new-9',
    name: 'سيروم الهيالورونيك أسيد المركز',
    description: 'سيروم لترطيب البشرة المكثف وملء الخطوط الدقيقة والتجاعيد لتبدو البشرة أكثر شباباً وحيوية ونضارة طوال اليوم.',
    price: 55,
    quantity: 80,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/hyaluronic/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 165
  },
  {
    id: 'beauty-new-10',
    name: 'مجموعة ظلال العيون بـ 12 لوناً مطفأ ولامعاً',
    description: 'لوحة ألوان ظلال عيون غنية بالصبغة الفاخرة وسهلة الدمج لتمنحك مكياج عيون ساحر وجريء للنهار والمساء.',
    price: 42,
    quantity: 45,
    category: 'makeup',
    image: 'https://picsum.photos/seed/eyeshadow/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 78
  },
  {
    id: 'beauty-new-11',
    name: 'زيت مقوي ومغذي لبصيلات الشعر',
    description: 'تركيبة فريدة غنية بالزيوت الطبيعية السبعة المغذية والفيتامينات لإنبات وتكثيف الشعر ومنع التساقط بفعالية.',
    price: 48,
    quantity: 65,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/hairoil/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 91
  },
  {
    id: 'beauty-new-12',
    name: 'عطر العود والمسك الشرقي الفخم',
    description: 'عطر شرقي فاخر وساحر يجمع بين دفء العود الأصيل وجاذبية المسك الأبيض بنسبة ثبات تدوم لأكثر من 48 ساعة.',
    price: 140,
    quantity: 30,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/oudperfume/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 122
  },
  {
    id: 'beauty-new-13',
    name: 'لوشن مرطب ومفتح للجسم بالكرز والياسمين',
    description: 'لوشن معطر ومرطب عميق للجسم يمنحك بشرة حريرية وناعمة ورائحة فواحة مميزة تأسر الحواس طوال اليوم.',
    price: 29,
    quantity: 100,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/bodylotion/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 89
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customerId: 'CUST-1',
    customerName: 'أحمد محمد',
    items: [{ productId: '1', name: 'ساعة ذكية برو', quantity: 1, price: 299 }],
    total: 299,
    status: 'delivered',
    date: '2024-03-15'
  },
  {
    id: 'ORD-002',
    customerId: 'CUST-2',
    customerName: 'سارة خالد',
    items: [{ productId: '3', name: 'قميص قطني عصري', quantity: 2, price: 45 }],
    total: 90,
    status: 'processing',
    date: '2024-03-20'
  }
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'VEN-1',
    name: 'عبدالله علي',
    email: 'abdullah@example.com',
    storeName: 'عالم التقنية',
    category: 'إلكترونيات',
    sales: 15400,
    rating: 4.8,
    status: 'active',
    joinDate: '2023-01-10'
  },
  {
    id: 'VEN-2',
    name: 'ليلى حسن',
    email: 'laila@example.com',
    storeName: 'أزياء ليلى',
    category: 'أزياء',
    sales: 8200,
    rating: 4.5,
    status: 'pending',
    joinDate: '2024-02-15'
  }
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-1',
    name: 'أحمد محمد',
    email: 'ahmed@example.com',
    totalOrders: 5,
    totalSpent: 1250,
    status: 'active'
  },
  {
    id: 'CUST-2',
    name: 'سارة خالد',
    email: 'sara@example.com',
    totalOrders: 2,
    totalSpent: 180,
    status: 'active'
  }
];
