import { Product, Category, Order, Vendor, Customer } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'الكل', icon: 'LayoutGrid' },
  { id: 'electronics', name: 'إلكترونيات', icon: 'Smartphone' },
  { id: 'mobiles', name: 'موبايلات', icon: 'Smartphone', parentId: 'electronics' },
  { id: 'tvs', name: 'تلفزيونات', icon: 'Tv', parentId: 'electronics' },
  { id: 'computer_world', name: 'عالم الكمبيوتر', icon: 'Cpu', parentId: 'electronics' },
  { id: 'headphones', name: 'سماعات', icon: 'Headphones', parentId: 'electronics' },
  { id: 'smartwatches', name: 'ساعات ذكية', icon: 'Watch', parentId: 'electronics' },
  { id: 'laptops', name: 'لابتوب', icon: 'Laptop', parentId: 'electronics' },
  { id: 'speakers', name: 'سبيكر', icon: 'Speaker', parentId: 'electronics' },
  { id: 'mobile_accessories', name: 'اكسسوارات موبايل', icon: 'Cable', parentId: 'electronics' },
  { id: 'printer_supplies', name: 'مستلزمات طابعة', icon: 'Printer', parentId: 'electronics' },
  { id: 'cameras', name: 'كاميرات', icon: 'Camera', parentId: 'electronics' },
  { id: 'fashion', name: 'أزياء', icon: 'Shirt' },
  { id: 'men', name: 'رجالي', icon: 'User', parentId: 'fashion' },
  { id: 'women', name: 'نسائي', icon: 'User', parentId: 'fashion' },
  { id: 'girls', name: 'بناتي', icon: 'Baby', parentId: 'fashion' },
  { id: 'boys', name: 'ولادي', icon: 'Baby', parentId: 'fashion' },
  { id: 'kids', name: 'الأطفال', icon: 'Baby', parentId: 'fashion' },
  { id: 'travel_essentials', name: 'مستلزمات السفر', icon: 'Briefcase', parentId: 'fashion' },
  { id: 'shoes', name: 'الأحذية', icon: 'Footprints', parentId: 'fashion' },
  { id: 'watches_fashion', name: 'الساعات', icon: 'Watch', parentId: 'fashion' },
  { id: 'sportswear', name: 'ملابس رياضية', icon: 'Dumbbell', parentId: 'fashion' },
  { id: 'home', name: 'المنزل', icon: 'Home' },
  { id: 'cleaning_tools', name: 'أدوات التنظيف', icon: 'BrushCleaning', parentId: 'home' },
  { id: 'bedding', name: 'الفراش', icon: 'Bed', parentId: 'home' },
  { id: 'storage_organization', name: 'التخزين والتنظيم', icon: 'Archive', parentId: 'home' },
  { id: 'furniture', name: 'الأثاث', icon: 'Sofa', parentId: 'home' },
  { id: 'home_appliances', name: 'الأجهزة المنزلية', icon: 'Microwave', parentId: 'home' },
  { id: 'waste_recycling', name: 'النفايات وإعادة التدوير', icon: 'Recycle', parentId: 'home' },
  { id: 'home_decor', name: 'ديكور المنزل', icon: 'Palette', parentId: 'home' },
  { id: 'beepharma', name: 'BeePharma', icon: 'Bug' },
  { id: 'honey', name: 'عسل', icon: 'Droplets', parentId: 'beepharma' },
  { id: 'creams', name: 'كريمات', icon: 'Sparkles', parentId: 'beepharma' },
  { id: 'herbs', name: 'أعشاب', icon: 'Leaf', parentId: 'beepharma' },
  { id: 'shampoos', name: 'شامبوهات', icon: 'Bath', parentId: 'beepharma' },
  { id: 'incense', name: 'بخور', icon: 'Wind', parentId: 'beepharma' },
  { id: 'natural_soap', name: 'صابون طبيعي', icon: 'Square', parentId: 'beepharma' },
  { id: 'therapeutic_mixtures', name: 'خلطات علاجية', icon: 'FlaskConical', parentId: 'beepharma' },
  { id: 'beauty', name: 'الجمال', icon: 'Sparkles' },
  { id: 'skin_care', name: 'العناية بالبشرة', icon: 'Sparkles', parentId: 'beauty' },
  { id: 'makeup', name: 'المكياج', icon: 'Palette', parentId: 'beauty' },
  { id: 'hair_care', name: 'العناية بالشعر', icon: 'Scissors', parentId: 'beauty' },
  { id: 'mens_perfumes', name: 'عطور رجالية', icon: 'Flame', parentId: 'beauty' },
  { id: 'womens_perfumes', name: 'عطور نسائية', icon: 'Flame', parentId: 'beauty' },
  { id: 'mens_care', name: 'العناية بالرجال', icon: 'User', parentId: 'beauty' },
  { id: 'seasonal_products', name: 'منتجات موسمية', icon: 'Sun', parentId: 'beauty' },
  { id: 'beauty_devices', name: 'أجهزة الجمال', icon: 'Zap', parentId: 'beauty' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'mobiles-new-1',
    name: 'IPhone 16 PRO MAX',
    description:' . ',
    price: 1200,
    quantity: 45,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 124
  },
 {
    id: 'mobiles-new-2',
    name: 'Samsung ULTRA 26',
    description:' . ',
    price: 1200,
    quantity: 55,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 110
  },
   {
    id: 'mobiles-new-3',
    name: 'Xiaomi Redmi Note 14 Pro Plus 5G',
    description:' . ',
    price: 299,
    quantity: 65,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 132
  },
   {
    id: 'mobiles-new-4',
    name: 'Xiaomi 15 Ultra',
    description:' . ',
    price: 1200,
    quantity: 65,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 122
  },
   {
    id: 'mobiles-new-5',
    name: 'iPhone 15 Pro Max',
    description:' . ',
    price: 1099,
    quantity: 75,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 155
  },
   {
    id: 'mobiles-new-6',
    name: 'Apple iPhone 16 Pro Max',
    description:' . ',
    price: 1099,
    quantity: 35,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 129
  },
    {
    id: 'mobiles-new-7',
    name: 'Xiaomi 17 Pro Max',
    description:' . ',
    price: 980,
    quantity: 45,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 154
  },
    {
    id: 'mobiles-new-8',
    name: 'Samsung Galaxy S22 Ultra',
    description:' . ',
    price: 650,
    quantity: 75,
    category: 'mobiles',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 174
  },
   {
    id: 'tvs-new-1',
    name: 'Sony BRAVIA XR-48A90K 48" A90K Smart OLED 4K UHD TV with HDR',
    description:' . ',
    price: 1299,
    quantity: 45,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 174
  },
   {
    id: 'tvs-new-2',
    name: 'Sony BRAVIA 8 (K55XR80) Smart OLED 4K TV with HDR (55")',
    description:' . ',
    price: 1500,
    quantity: 45,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 174
  },
     {
    id: 'tvs-new-3',
    name: 'LG OLED55C5PUA OLED Evo AI C5 Smart 4K TV (55")',
    description:' . ',
    price: 1199,
    quantity: 45,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 174
  },
     {
    id: 'tvs-new-4',
    name: 'LG C6 OLED Evo AI Smart 4K TV (55")',
    description:' . ',
    price: 1199,
    quantity: 65,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 105
  },
     {
    id: 'tvs-new-5',
    name: 'Samsung S95H OLED Vision AI Smart 4K TV (55")',
    description:' . ',
    price: 2200,
    quantity: 35,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 74
  },
     {
    id: 'tvs-new-6',
    name: 'Samsung S90H',
    description:' . ',
    price: 1799,
    quantity: 65,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 155
  },
     {
    id: 'tvs-new-7',
    name: 'Samsung S85H',
    description:' . ',
    price: 1399,
    quantity: 55,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 100
  },
     {
    id: 'tvs-new-8',
    name: 'Samsung Neo QLED AI بدقة 8K',
    description:' . ',
    price: 700,
    quantity: 75,
    category: 'tvs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 115
  },
   {
    id: 'elec-new-1',
    name: 'Samsung Odyssey G9 G91F 49" Dual 1440p HDR',
    description:' . ',
    price: 700,
    quantity: 55,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 145
  },
     {
    id: 'elec-new-2',
    name: 'HP EliteStudio 8 27 G1i All in One AI PC',
    description:' . ',
    price: 4600,
    quantity: 45,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 145
  },
     {
    id: 'elec-new-3',
    name: 'Redragon S101-3 PRO Gaming Keyboard and Mouse',
    description:' . ',
    price: 40,
    quantity: 25,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 155
  },
     {
    id: 'elec-new-4',
    name: 'Dowinx Big and Tall Gaming Chair',
    description:' . ',
    price: 160,
    quantity: 55,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 135
  },
     {
    id: 'elec-new-5',
    name: 'Samsung Neo QLED AI بدقة 8K',
    description:' . ',
    price: 700,
    quantity: 35,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 155
  },
     {
    id: 'elec-new-6',
    name: 'NUBWO Wireless Gaming Headset with Mic for Ps5 Ps4 PC, Zero Interference',
    description:' . ',
    price: 30,
    quantity: 25,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 125
  },
     {
    id: 'elec-new-7',
    name: 'Ultrawide Curved Gaming Monitor',
    description:' . ',
    price: 600,
    quantity: 35,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 105
  },
     {
    id: 'elec-new-8',
    name: 'PS5 - Sony PlayStation 5',
    description:' . ',
    price: 600,
    quantity: 65,
    category: 'computer_world',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 100
  },
      {
    id: 'headphones-new-1',
    name: 'Active Noise Cancelling Headphones',
    description:' . ',
    price: 42,
    quantity: 65,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 26
  },
      {
    id: 'headphones-new-2',
    name: 'Anker Noise Cancelling Earbuds',
    description:' . ',
    price: 28,
    quantity: 65,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 100
  },
      {
    id: 'headphones-new-3',
    name: 'Wireless Earbuds',
    description:' . ',
    price: 14,
    quantity: 75,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 150
  },
      {
    id: 'headphones-new-4',
    name: 'TOZO A1 Wireless Earbuds',
    description:' . ',
    price: 14,
    quantity: 55,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
      {
    id: 'headphones-new-5',
    name: 'Razer BlackShark V2 X Gaming Headset',
    description:' . ',
    price: 40,
    quantity: 35,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
      {
    id: 'headphones-new-6',
    name: 'Logitech G432 Wired Gaming Headset',
    description:' . ',
    price: 40,
    quantity: 75,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 130
  },
      {
    id: 'headphones-new-7',
    name: 'Apple AirPods 4 Wireless Earbuds',
    description:' . ',
    price: 99,
    quantity: 45,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 160
  },
      {
    id: 'headphones-new-8',
    name: 'Apple AirPods Pro 3 Wireless Earbuds',
    description:' . ',
    price: 200,
    quantity: 35,
    category: 'headphones',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
        {
    id: 'smartwatches-new-1',
    name: 'Smart Watch iPhone Samsung Android',
    description:' . ',
    price: 20,
    quantity: 35,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 110
  },
          {
    id: 'smartwatches-new-2',
    name: 'Google Pixel Watch',
    description:' . ',
    price: 400,
    quantity: 25,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 120
  },
          {
    id: 'smartwatches-new-3',
    name: 'Sports Modes Smartwatch with 1.83" HD',
    description:' . ',
    price: 20,
    quantity: 25,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },
          {
    id: 'smartwatches-new-4',
    name: 'Blackview 2026 Smart Watch',
    description:' . ',
    price: 25,
    quantity: 65,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 140
  },
          {
    id: 'smartwatches-new-5',
    name: 'Tracker with Stress Management',
    description:' . ',
    price: 65,
    quantity: 65,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 110
  },
          {
    id: 'smartwatches-new-6',
    name: 'Smart Watch for Women, Answer/Make Call',
    description:' . ',
    price: 30,
    quantity: 45,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 105
  },
          {
    id: 'smartwatches-new-7',
    name: 'Health Fitness Tracker',
    description:' . ',
    price: 40,
    quantity: 55,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 130
  },
          {
    id: 'smartwatches-new-8',
    name: 'Smart Watch with Alexa',
    description:' . ',
    price: 30,
    quantity: 35,
    category: 'smartwatches',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 140
  },
      {
    id: 'laptops-new-1',
    name: 'Apple 2026 MacBook Pro Laptop',
    description:' . ',
    price: 2375,
    quantity: 45,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 130
  },
        {
    id: 'laptops-new-2',
    name: 'Apple 2026 MacBook Air',
    description:' . ',
    price: 1400,
    quantity: 35,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
        {
    id: 'laptops-new-3',
    name: 'Apple 2026 MacBook Neo',
    description:' . ',
    price: 650,
    quantity: 25,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
        {
    id: 'laptops-new-4',
    name: 'HP OmniBook 5 16 inch Next Gen AI PC',
    description:' . ',
    price: 800,
    quantity: 25,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 120
  },
        {
    id: 'laptops-new-5',
    name: 'HP OmniBook 3 16 inch Laptop PC',
    description:' . ',
    price: 550,
    quantity: 55,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 180
  },
        {
    id: 'laptops-new-6',
    name: 'HP OmniBook 3 17.3 inch Laptop PC',
    description:' . ',
    price: 450,
    quantity: 65,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
        {
    id: 'laptops-new-7',
    name: 'Samsung 14" Galaxy Chromebook Go Laptop PC',
    description:' . ',
    price: 200,
    quantity: 85,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 170
  },
        {
    id: 'laptops-new-8',
    name: 'ASUS 15.6” Vivobook Go Slim Laptop',
    description:' . ',
    price: 300,
    quantity: 65,
    category: 'laptops',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 180
  },
        {
    id: 'speakers-new-1',
    name: 'Floorstanding Speaker',
    description:' . ',
    price: 999,
    quantity: 65,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 180
  },
        {
    id: 'speakers-new-2',
    name: 'KEF R3 Meta (Black Gloss, Pair)',
    description:' . ',
    price: 2500,
    quantity: 35,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
          {
    id: 'speakers-new-3',
    name: 'Floorstanding Speaker, Black Textured Wood Grain Vinyl',
    description:' . ',
    price: 550,
    quantity: 75,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 140
  },
          {
    id: 'speakers-new-4',
    name: 'Polk Monitor XT70 Large Tower Speaker',
    description:' . ',
    price: 320,
    quantity: 65,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },
          {
    id: 'speakers-new-5',
    name: 'Polk Signature Elite ES10 Surround Sound Speakers',
    description:' . ',
    price: 250,
    quantity: 85,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 150
  },
          {
    id: 'speakers-new-6',
    name: 'Polk Audio OWM3 Wall and Bookshelf Speakers',
    description:' . ',
    price: 200,
    quantity: 55,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 170
  },
          {
    id: 'speakers-new-7',
    name: 'Pair of Bookshelf or Surround Sound Speakers',
    description:' . ',
    price: 150,
    quantity: 75,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 120
  },
          {
    id: 'speakers-new-8',
    name: 'Klipsch R-51M Bookshelf Speaker (Pair), Black',
    description:' . ',
    price: 290,
    quantity: 45,
    category: 'speakers',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 130
  },
          {
    id: 'mobile_accessories-new-1',
    name: 'Fast iPhone Charger, iPhone Charger Fast Charging',
    description:' . ',
    price: 19,
    quantity: 95,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 150
  },
            {
    id: 'mobile_accessories-new-2',
    name: 'iPhone Fast Charger Apple Certified',
    description:' . ',
    price: 29,
    quantity: 55,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 170
  },
            {
    id: 'mobile_accessories-new-3',
    name: 'USB C Cable 60W Fast Charging 2 Pack 6FT',
    description:' . ',
    price: 16,
    quantity: 15,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 120
  },
            {
    id: 'mobile_accessories-new-4',
    name: 'Durcord USB C Cable',
    description:' . ',
    price: 13,
    quantity: 45,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 110
  },
            {
    id: 'mobile_accessories-new-5',
    name: 'JETech Case for iPhone 16',
    description:' . ',
    price: 19,
    quantity: 35,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 160
  },
            {
    id: 'mobile_accessories-new-6',
    name: 'TAURI for iPhone 16 Case',
    description:' . ',
    price: 29,
    quantity: 25,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 130
  },
            {
    id: 'mobile_accessories-new-7',
    name: 'FNTCASE for iPhone 16 Case',
    description:' . ',
    price: 10,
    quantity: 25,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 160
  },
            {
    id: 'mobile_accessories-new-8',
    name: 'FNTCASE for iPhone 16 Case',
    description:' . ',
    price: 15,
    quantity: 55,
    category: 'mobile_accessories',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 120
  },
            {
    id: 'printer_supplies-new-1',
    name: 'HP Laserjet Pro 3001dw Wireless Black & White Printer',
    description:' . ',
    price: 199,
    quantity: 65,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 100
  },
            {
    id: 'printer_supplies-new-2',
    name: 'HP LaserJet M209dw Wireless Printer',
    description:' . ',
    price: 160,
    quantity: 55,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 110
  },
              {
    id: 'printer_supplies-new-3',
    name: 'Brother HL-L2405W Wireless Compact Monochrome Laser Printer',
    description:' . ',
    price: 140,
    quantity: 35,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 180
  },
              {
    id: 'printer_supplies-new-4',
    name: 'Compact Monochrome Multi-Function Laser Printe',
    description:' . ',
    price: 210,
    quantity: 75,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 130
  },
              {
    id: 'printer_supplies-new-5',
    name: 'Monochrome Laser Printer with Mobile Printing',
    description:' . ',
    price: 140,
    quantity: 25,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 160
  },
              {
    id: 'printer_supplies-new-6',
    name: 'HP LaserJet Wireless Black & White Printer',
    description:' . ',
    price: 130,
    quantity: 45,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
              {
    id: 'printer_supplies-new-7',
    name: 'HP Laserjet MFP M140w Wireless Black & White Printer',
    description:' . ',
    price: 140,
    quantity: 35,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 140
  },
     {
    id: 'printer_supplies-new-8',
    name: 'HP LaserJet MFP M234sdw Wireless Printer',
    description:' . ',
    price: 220,
    quantity: 25,
    category: 'printer_supplies',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 110
  },
     {
    id: 'cameras-new-1',
    name: 'Vlogging Cameras with 1'' CMOS & 4K/120fps Vlog Camera',
    description:' . ',
    price: 440,
    quantity: 55,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 150
  },
       {
    id: 'cameras-new-2',
    name: 'Xtra Muse, Vlogging Camera',
    description:' . ',
    price: 420,
    quantity: 55,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 170
  },
       {
    id: 'cameras-new-3',
    name: 'Canon EOS Rebel T7 DSLR Camera',
    description:' . ',
    price: 480,
    quantity: 75,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 130
  },
       {
    id: 'cameras-new-4',
    name: 'Canon EOS R100 Mirrorless Camera',
    description:' . ',
    price: 490,
    quantity: 65,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 170
  },
       {
    id: 'cameras-new-5',
    name: 'Canon EOS RP Full-Frame Mirrorless Interchangeable',
    description:' . ',
    price: 1099,
    quantity: 45,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
       {
    id: 'cameras-new-6',
    name: 'Sony a7 III Full-Frame Mirrorless',
    description:' . ',
    price: 1899,
    quantity: 25,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 130
  },
       {
    id: 'cameras-new-7',
    name: 'Sony Alpha 7 IV Full-Frame Mirrorless Interchangeable',
    description:' . ',
    price: 1299,
    quantity: 75,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
       {
    id: 'cameras-new-8',
    name: 'Sony Alpha 7 V Full-Frame Hybrid Mirrorless Camera',
    description:' . ',
    price: 3099,
    quantity: 35,
    category: 'cameras',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 110
  },
       {
    id: 'men-new-1',
    name: 'COOFANDY Mens Button Down Short',
    description:' . ',
    price: 18,
    quantity: 65,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 120
  },
       {
    id: 'men-new-2',
    name: 'J.VER Mens Dress Shirts Solid Long',
    description:' . ',
    price: 20,
    quantity: 65,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
         {
    id: 'men-new-3',
    name: 'Mens Linen Shirts Short Sleeve Casual Shirts',
    description:' . ',
    price: 31,
    quantity: 25,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
         {
    id: 'men-new-4',
    name: 'Sailwind Mens Muscle Henley Shirts Lightweight',
    description:' . ',
    price: 15,
    quantity: 35,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 170
  },
         {
    id: 'men-new-5',
    name: 'Mens Henley Shirt Casual Button Short Sleeve',
    description:' . ',
    price: 15,
    quantity: 65,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 110
  },
         {
    id: 'men-new-6',
    name: 'Shirts Short Sleeve Button Cotton T Shirts | Summer',
    description:' . ',
    price: 18,
    quantity: 55,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 150
  },
         {
    id: 'men-new-7',
    name: 'Mens Casual Button Down Shirts Short Sleeve Textured Summer',
    description:' . ',
    price: 25,
    quantity: 35,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
         {
    id: 'men-new-8',
    name: 'Mens Polo Shirts Short Sleeve Casual Summer',
    description:' . ',
    price: 29,
    quantity: 45,
    category: 'men',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 140
  },
         {
    id: 'women-new-1',
    name: 'khalat Muslim Prayer Dress Abaya Solid',
    description:' . ',
    price: 40,
    quantity: 65,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 160
  },
         {
    id: 'women-new-2',
    name: 'Prien Prayer Dress For Women Cotton Muslim Abaya',
    description:' . ',
    price: 39,
    quantity: 65,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 190
  },
           {
    id: 'women-new-3',
    name: 'Womens Solid Muslim One-Piece',
    description:' . ',
    price: 38,
    quantity: 35,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 110
  },
           {
    id: 'women-new-4',
    name: 'Muslim Abaya Dress for Women',
    description:' . ',
    price: 34,
    quantity: 35,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 110
  },
           {
    id: 'women-new-5',
    name: 'Muslim Dress for Women Pakistani Kaftan',
    description:' . ',
    price: 37,
    quantity: 55,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
           {
    id: 'women-new-6',
    name: 'Muslim Prayer Abaya Women Jilbab with Hijab',
    description:' . ',
    price: 39,
    quantity: 25,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 170
  },
           {
    id: 'women-new-7',
    name: 'Women Prayer Clothes with Hijab Muslim Outfits Long',
    description:' . ',
    price: 23,
    quantity: 35,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 130
  },
           {
    id: 'women-new-8',
    name: 'Muslim Abayas Dress with Hijabs Long Sleeve Modest',
    description:' . ',
    price: 40,
    quantity: 45,
    category: 'women',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 120
  },
           {
    id: 'girls-new-1',
    name: 'فساتين صيفية للبنات',
    description:' . ',
    price: 15,
    quantity: 35,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 110
  },
           {
    id: 'girls-new-2',
    name: 'فستان صيفي للأميرات للبنات)',
    description:' . ',
    price: 15,
    quantity: 65,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 180
  },
             {
    id: 'girls-new-3',
    name: 'فستان مكشكش للبنات الصغيرات',
    description:' . ',
    price: 16,
    quantity: 45,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
             {
    id: 'girls-new-4',
    name: 'فساتين دانتيل بأكمام مكشكشة للأطفال الصغار',
    description:' . ',
    price: 14,
    quantity: 65,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
             {
    id: 'girls-new-5',
    name: 'فستان صيفي بلا أكمام ومزين بكشكشة للطفلات الصغيرات',
    description:' . ',
    price: 17,
    quantity: 25,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 170
  },
             {
    id: 'girls-new-6',
    name: 'ملابس صيفية للبنات الصغيرات',
    description:' . ',
    price: 15,
    quantity: 55,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 140
  },
             {
    id: 'girls-new-7',
    name: 'أزياء ملابس البنات: تيشيرتات مطبوعة وتصاميم كاجوال',
    description:' . ',
    price: 35,
    quantity: 75,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 150
  },
      {
    id: 'girls-new-8',
    name: 'طقم ملابس للبنات بلوزة بأكمام قصيرة',
    description:' . ',
    price: 25,
    quantity: 35,
    category: 'girls',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
      {
    id: 'travel_essentials-new-1',
    name: 'حقيبة التنقل اليومي',
    description:' . ',
    price: 250,
    quantity: 45,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 120
  },
     {
    id: 'travel_essentials-new-2',
    name: 'حقيبة ظهر بعجلات قابلة للفصل ومناسبة للمقصورة',
    description:' . ',
    price: 130,
    quantity: 35,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 140
  },
       {
    id: 'travel_essentials-new-3',
    name: 'حقيبة ظهر للسفر بعجلات قابلة للتوسيع',
    description:' . ',
    price: 67,
    quantity: 45,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 110
  },
       {
    id: 'travel_essentials-new-4',
    name: 'حقيبة ظهر بعجلات للنساء',
    description:' . ',
    price: 65,
    quantity: 65,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
       {
    id: 'travel_essentials-new-5',
    name: 'حقيبة ذو غلاف صلب وخفيفة الوزن',
    description:' . ',
    price: 70,
    quantity: 35,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
       {
    id: 'travel_essentials-new-6',
    name: 'حقيبة سفر صغيرة',
    description:' . ',
    price: 85,
    quantity: 55,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 150
  },
       {
    id: 'travel_essentials-new-7',
    name: 'حقيبة سفر جلدية كبيرة',
    description:' . ',
    price: 95,
    quantity: 65,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 140
  },
       {
    id: 'travel_essentials-new-8',
    name: 'حقيبة سفر صغيرة للرحلات السياحية',
    description:' . ',
    price: 75,
    quantity: 35,
    category: 'travel_essentials',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 130
  },
       {
    id: 'shoes-new-1',
    name: 'حذاء رجالي للمناسبات',
    description:' . ',
    price: 95,
    quantity: 75,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
       {
    id: 'shoes-new-1',
    name: 'حذاء رجالي للمناسبات',
    description:' . ',
    price: 75,
    quantity: 45,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
         {
    id: 'shoes-new-2',
    name: 'جزمة نسائية عصرية',
    description:' . ',
    price: 75,
    quantity: 35,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 150
  },
         {
    id: 'shoes-new-3',
    name: 'خفافة رجالية عصرية',
    description:' . ',
    price: 45,
    quantity: 25,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 110
  },
         {
    id: 'shoes-new-4',
    name: 'كعب نسائي للمناسبات',
    description:' . ',
    price: 95,
    quantity: 45,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
         {
    id: 'shoes-new-5',
    name: 'حذاء نسائي رياضي',
    description:' . ',
    price: 75,
    quantity: 75,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
         {
    id: 'shoes-new-6',
    name: 'كلاش بناتي جميل',
    description:' . ',
    price: 25,
    quantity: 55,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
         {
    id: 'shoes-new-7',
    name: 'بوت ولادي ',
    description:' . ',
    price: 55,
    quantity: 45,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
         {
    id: 'shoes-new-8',
    name: 'حذاء رجالي رياضي',
    description:' . ',
    price: 35,
    quantity: 25,
    category: 'shoes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 130
  },
         {
    id: 'watches_fashion-new-1',
    name: 'ساعة يد نسائية ذهبية ',
    description:' . ',
    price: 365,
    quantity: 25,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 110
  },
         {
    id: 'watches_fashion-new-2',
    name: 'ساعة يد من شركة Rolex ',
    description:' . ',
    price: 7500,
    quantity: 55,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },

           {
    id: 'watches_fashion-new-3',
    name: 'ساعة يد شبابية من ROLEX ',
    description:' . ',
    price: 9500,
    quantity: 45,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 120
  },

           {
    id: 'watches_fashion-new-4',
    name: 'ساعة يد ولادية ذكية ',
    description:' . ',
    price: 65,
    quantity: 35,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 100
  },

           {
    id: 'watches_fashion-new-5',
    name: 'ساعة يد بناتية ذكية ',
    description:' . ',
    price: 65,
    quantity: 25,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 110
  },

           {
    id: 'watches_fashion-new-6',
    name: 'ساعة يد رجالية من شركة OVLES ',
    description:' . ',
    price: 95,
    quantity: 45,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },

           {
    id: 'watches_fashion-new-7',
    name: 'ساعة يد رجالية من شركة LN LENQIN ',
    description:' . ',
    price: 200,
    quantity: 55,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },

           {
    id: 'watches_fashion-new-8',
    name: 'ساعة يد نسائية مرصعة بالجواهر ',
    description:' . ',
    price: 565,
    quantity: 35,
    category: 'watches_fashion',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
    {
    id: 'sportswear-new-1',
    name: 'جاكيت رياضي من شركة adidas ',
    description:' . ',
    price: 565,
    quantity: 45,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
      {
    id: 'sportswear-new-2',
    name: 'طقم رياضي قطني من شركة Puma',
    description:' . ',
    price: 65,
    quantity: 45,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 110
  },
      {
    id: 'sportswear-new-3',
    name: 'طاقية رياضية من شركة Nike',
    description:' . ',
    price: 50,
    quantity: 65,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 110
  },
      {
    id: 'sportswear-new-4',
    name: 'طقم رياضي كامل من شركة adidas',
    description:' . ',
    price: 500,
    quantity: 25,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
      {
    id: 'sportswear-new-5',
    name: 'اسوارة قماشية قطنية رياضية من شركة Nike',
    description:' . ',
    price: 50,
    quantity: 35,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 100
  },
      {
    id: 'sportswear-new-6',
    name: 'بيجامة رياضية من شركة Nike ',
    description:' . ',
    price: 565,
    quantity: 45,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
      {
    id: 'sportswear-new-7',
    name: 'شورت رياضي من شركة adidas ',
    description:' . ',
    price: 65,
    quantity: 35,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 120
  },
      {
    id: 'sportswear-new-8',
    name: 'سترة رياضية من شركة adidas ',
    description:' . ',
    price: 500,
    quantity: 65,
    category: 'sportswear',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 130
  },
        {
    id: 'bedding-new-1',
    name: 'وسادة قطنية ناعمة من شركة Saatva',
    description:' . ',
    price: 50,
    quantity: 65,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 110
  },
          {
    id: 'bedding-new-2',
    name: 'مفرش مزدوج ولادي قطني من شركة Anichini',
    description:' . ',
    price: 40,
    quantity: 65,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 100
  },
        {
    id: 'bedding-new-3',
    name: 'مفرش ولادي صغير من شركة Anichini',
    description:' . ',
    price: 90,
    quantity: 75,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 110
  },
        {
    id: 'bedding-new-4',
    name: 'مفرش مزدوج قطني ناعم من شركة Welspun Group',
    description:' . ',
    price: 200,
    quantity: 25,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 100
  },
        {
    id: 'bedding-new-5',
    name: 'مفرش تخت مزدوج من شركة Tempur-Sealy',
    description:' . ',
    price: 99,
    quantity: 65,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 190
  },
        {
    id: 'bedding-new-6',
    name: 'مفرش قطني 100% من شركة Frette',
    description:' . ',
    price: 60,
    quantity: 95,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
        {
    id: 'bedding-new-7',
    name: 'وسادة قطنية ناعمة من شركة Coop Sleep Goods',
    description:' . ',
    price: 50,
    quantity: 45,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
        {
    id: 'bedding-new-8',
    name: 'طقم وسائد من شركة  CozyLux وسائد سرير ناعمة وداعمة بحشوة بديلة للريش',
    description:' . ',
    price: 40,
    quantity: 35,
    category: 'bedding',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 130
  },
        {
    id: 'storage_organization-new-1',
    name: 'طقم منظمات أدراج المطبخ',
    description:' . ',
    price: 32,
    quantity: 55,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 130
  },
  {
 id: 'storage_organization-new-2',
    name: 'طقم لتخزين الملابس للأطفال',
    description:' . ',
    price: 20,
    quantity: 35,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 110
  }, 
        {
    id: 'storage_organization-new-3',
    name: 'مخزن أدراج للأحذية',
    description:' . ',
    price: 65,
    quantity: 65,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 170
  },

          {
    id: 'storage_organization-new-4',
    name: 'طقم رفوف للزرع',
    description:' . ',
    price: 39,
    quantity: 45,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 130
  },

          {
    id: 'storage_organization-new-5',
    name: 'طقم أدراج تخزين الملابس',
    description:' . ',
    price: 45,
    quantity: 35,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 150
  },

          {
    id: 'storage_organization-new-6',
    name: 'طقم رفوف للحمام',
    description:' . ',
    price: 29,
    quantity: 25,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },

          {
    id: 'storage_organization-new-7',
    name: 'طقم أدراج للمنظفات',
    description:' . ',
    price: 50,
    quantity: 35,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
        {
    id: 'storage_organization-new-8',
    name: 'طقم أدراج مناشف',
    description:' . ',
    price: 40,
    quantity: 25,
    category: 'storage_organization',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
        {
    id: 'home_appliances-new-1',
    name: 'غسالة LG حوض كبير',
    description:' . ',
    price: 400,
    quantity: 25,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
          {
    id: 'home_appliances-new-2',
    name: 'خلاط منزلي كبير من شركة Samsung',
    description:' . ',
    price: 400,
    quantity: 25,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
          {
    id: 'home_appliances-new-3',
    name: 'الميكروويف المنزلي من شركة LG',
    description:' . ',
    price: 200,
    quantity: 25,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
          {
    id: 'home_appliances-new-4',
    name: 'مكنسة كهربائية منزلية من شركة LG',
    description:' . ',
    price: 100,
    quantity: 35,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },
          {
    id: 'home_appliances-new-5',
    name: 'فرن منزلي من 6 رؤوس من شركة LG',
    description:' . ',
    price: 300,
    quantity: 45,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 170
  },
          {
    id: 'home_appliances-new-6',
    name: 'فرن منزلي 5 رؤوس من شركة Frigidaire',
    description:' . ',
    price: 100,
    quantity: 45,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
          {
    id: 'home_appliances-new-7',
    name: 'براد مكتبي من شركة LG',
    description:' . ',
    price: 200,
    quantity: 45,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 110
  },
          {
    id: 'home_appliances-new-8',
    name: 'براد منزلي من شركة LG ',
    description:' . ',
    price: 500,
    quantity: 35,
    category: 'home_appliances',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },
        {
    id: 'waste_recycling-new-1',
    name: 'سلة مهملات ذكية من شركة Samsung',
    description:' . ',
    price: 50,
    quantity: 35,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 110
  },
        {
    id: 'waste_recycling-new-2',
    name: 'علبة قفازات ذو الاستخدام لمرة واحدة',
    description:' . ',
    price: 0.5,
    quantity: 65,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 10
  },
          {
    id: 'waste_recycling-new-3',
    name: 'قفازات معقّمة',
    description:' . ',
    price: 4,
    quantity: 25,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 40
  },
          {
    id: 'waste_recycling-new-4',
    name: 'حافظات الزجاج المكسور',
    description:' . ',
    price: 1.99,
    quantity: 95,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 90
  },
          {
    id: 'waste_recycling-new-5',
    name: 'أكياس مهملات للسلات الصغيرة',
    description:' . ',
    price: 0.5,
    quantity: 25,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 10
  },
          {
    id: 'waste_recycling-new-6',
    name: 'سلة مهملات منزلية',
    description:' . ',
    price: 1,
    quantity: 55,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
          {
    id: 'waste_recycling-new-7',
    name: 'سلة مهملات مكتبية ذكية من شركة LG',
    description:' . ',
    price: 50,
    quantity: 45,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
          {
    id: 'waste_recycling-new-8',
    name: 'أكياس نايلون للنفايات',
    description:' . ',
    price: 0.5,
    quantity: 25,
    category: 'waste_recycling',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 130
  },
          {
    id: 'home_decor-new-1',
    name: 'سجادة أرضية كبيرة لغرفة الجلوس',
    description:' . ',
    price: 25,
    quantity: 45,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 110
  },
          {
    id: 'home_decor-new-2',
    name: 'لوحة فنية كبيرة',
    description:' . ',
    price: 5,
    quantity: 55,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 120
  },
            {
    id: 'home_decor-new-3',
    name: 'برادي غرف الجلوس',
    description:' . ',
    price: 20,
    quantity: 25,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 110
  },
            {
    id: 'home_decor-new-4',
    name: 'كرسي هزاز مدور',
    description:' . ',
    price: 15,
    quantity: 25,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 170
  },
            {
    id: 'home_decor-new-5',
    name: 'عارضة خشب لوضع القطع المصمودة',
    description:' . ',
    price: 45,
    quantity: 35,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },
            {
    id: 'home_decor-new-6',
    name: 'مزهرية فاخرة ذو تصميم عربي',
    description:' . ',
    price: 25,
    quantity: 45,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 100
  },
            {
    id: 'home_decor-new-7',
    name: 'سجادة أرضية كبيرة لغرفة الضيافة',
    description:' . ',
    price: 45,
    quantity: 25,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
            {
    id: 'home_decor-new-8',
    name: 'سجادة أرضية صغيرة لغرفة الأطفال',
    description:' . ',
    price: 35,
    quantity: 35,
    category: 'home_decor',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 130
  },
         {
    id: 'bee-creams-new-1',
    name: 'كريم مرطب طبيعي',
    description:' . ',
    price: 10,
    quantity: 35,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
       {
    id: 'bee-creams-new-2',
    name: 'كريم خاص للتشققات',
    description:' . ',
    price: 9,
    quantity: 65,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 145
  },
       {
    id: 'bee-creams-new-3',
    name: 'كريم لإزالة حبوب الوحه',
    description:' . ',
    price: 13,
    quantity: 65,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
         {
    id: 'bee-creams-new-4',
    name: 'كريم مفتح بشرة',
    description:' . ',
    price: 20,
    quantity: 30,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
         {
    id: 'bee-creams-new-5',
    name: 'كريم مقاومة التجاعيد',
    description:' . ',
    price: 19,
    quantity: 75,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 160
  },
         {
    id: 'bee-creams-new-6',
    name: 'كريم مرطب شفاه',
    description:' . ',
    price: 16,
    quantity: 65,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 150
  },
         {
    id: 'bee-creams-new-7',
    name: 'كريم واقي شمسي',
    description:' . ',
    price: 12,
    quantity: 65,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 130
  },
         {
    id: 'bee-creams-new-8',
    name: 'كريم بالعسل طبيعي',
    description:' . ',
    price: 15,
    quantity: 45,
    category: 'creams',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 110
  },
       {
    id: 'bee-herbs-new-1',
    name: 'شاي الأعشاب المهدئة',
    description:' . ',
    price: 19,
    quantity: 65,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 110
  },
       {
    id: 'bee-herbs-new-2',
    name: 'اليانسون',
    description:' . ',
    price: 1.99,
    quantity: 65,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 140
  },
         {
    id: 'bee-herbs-new-3',
    name: 'الجينسنغ',
    description:' . ',
    price: 1.99,
    quantity: 75,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 100
  },
         {
    id: 'bee-herbs-new-4',
    name: 'إكليل الجبل',
    description:' . ',
    price: 2.99,
    quantity: 45,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 130
  },
         {
    id: 'bee-herbs-new-5',
    name: 'الكركم',
    description:' . ',
    price: 0.99,
    quantity: 25,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 130
  },
         {
    id: 'bee-herbs-new-6',
    name: 'النعناع',
    description:' . ',
    price: 0.99,
    quantity: 95,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 160
  },
         {
    id: 'bee-herbs-new-7',
    name: 'الزنجبيل',
    description:' . ',
    price: 0.99,
    quantity: 75,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 190
  },
         {
    id: 'bee-herbs-new-8',
    name: 'البابونج',
    description:' . ',
    price: 0.99,
    quantity: 45,
    category: 'herbs',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 100
  },
         {
    id: 'bee-shampoos-new-1',
    name: 'شامبو عسل السدر',
    description:' . ',
    price: 10,
    quantity: 45,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 100
  },
         {
    id: 'bee-shampoos-new-2',
    name: 'شامبو ضد القشرة',
    description:' . ',
    price: 7,
    quantity: 25,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 130
  },
           {
    id: 'bee-shampoos-new-3',
    name: 'شامبو بالعسل الطبيعي للأطفال',
    description:' . ',
    price: 17,
    quantity: 45,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 100
  },
           {
    id: 'bee-shampoos-new-4',
    name: 'شامبو لتحفيز نمو الشعر',
    description:' . ',
    price: 15,
    quantity: 65,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
           {
    id: 'bee-shampoos-new-5',
    name: 'شامبو ترطيب عميق بالشيا',
    description:' . ',
    price: 16,
    quantity: 25,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 170
  },
           {
    id: 'bee-shampoos-new-6',
    name: 'شامبو بالعسل والعكبر الطبيعي',
    description:' . ',
    price: 12,
    quantity: 65,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 150
  },
           {
    id: 'bee-shampoos-new-7',
    name: 'شامبو الخاص من BeePharma',
    description:' . ',
    price: 15,
    quantity: 65,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
           {
    id: 'bee-shampoos-new-8',
    name: 'شامبو القطران الطبيعي',
    description:' . ',
    price: 13,
    quantity: 35,
    category: 'shampoos',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 130
  },
           {
    id: 'bee-incense-new-1',
    name: 'بخور العود الفاخر',
    description:' . ',
    price: 13,
    quantity: 45,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 150
  },
           {
    id: 'bee-incense-new-2',
    name: 'بخور المكي',
    description:' . ',
    price: 19,
    quantity: 45,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 180
  },
             {
    id: 'bee-incense-new-3',
    name: 'بخور العطري السائل',
    description:' . ',
    price: 9,
    quantity: 35,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 150
  },
             {
    id: 'bee-incense-new-4',
    name: 'بخور الكلمنتان',
    description:' . ',
    price: 29,
    quantity: 55,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 170
  },
             {
    id: 'bee-incense-new-5',
    name: 'بخور الهندي',
    description:' . ',
    price: 18,
    quantity: 65,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 120
  },
             {
    id: 'bee-incense-new-6',
    name: 'بخور الماليزي',
    description:' . ',
    price: 25,
    quantity: 45,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
             {
    id: 'bee-incense-new-7',
    name: 'بخور الموروكي',
    description:' . ',
    price: 29,
    quantity: 35,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 110
  },
             {
    id: 'bee-incense-new-8',
    name: 'بخور االكمبودي',
    description:' . ',
    price: 19,
    quantity: 25,
    category: 'incense',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 120
  },
             {
    id: 'bee-natural_soap-new-1',
    name: 'صابون الغار',
    description:' . ',
    price: 2.99,
    quantity: 95,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 170
  },
            {
    id: 'bee-natural_soap-new-2',
    name: 'صابون الصبار الألوفيرا',
    description:' . ',
    price: 4.99,
    quantity: 65,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 110
  },
              {
    id: 'bee-natural_soap-new-3',
    name: 'صابون زيت الزيتون الطبيعي',
    description:' . ',
    price: 1.99,
    quantity: 85,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 120
  },
              {
    id: 'bee-natural_soap-new-4',
    name: 'صابون عسل النحل الطبيعي',
    description:' . ',
    price: 3.99,
    quantity: 75,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
              {
    id: 'bee-natural_soap-new-5',
    name: 'صابون الجلسرين',
    description:' . ',
    price: 1.99,
    quantity: 75,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 140
  },
              {
    id: 'bee-natural_soap-new-6',
    name: 'صابون الكركم',
    description:' . ',
    price: 5.99,
    quantity: 55,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 130
  },
              {
    id: 'bee-natural_soap-new-7',
    name: 'صابون الخاص من BeePharma',
    description:' . ',
    price: 4.99,
    quantity: 85,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
              {
    id: 'bee-natural_soap-new-8',
    name: 'صابون الكبريت',
    description:' . ',
    price: 4.99,
    quantity: 65,
    category: 'natural_soap',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 150
  },
     {
    id: 'bee-therapeutic_mixtures-new-1',
    name: 'عسل السدر مع الغذاء الملكي وحبوب اللقاح',
    description:' . ',
    price: 49,
    quantity: 75,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
     {
    id: 'bee-therapeutic_mixtures-new-2',
    name: 'الشمر',
    description:' . ',
    price: 19,
    quantity: 15,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 100
  },
       {
    id: 'bee-therapeutic_mixtures-new-3',
    name: 'عسل النحل مع الزنجبيل المطحون والليمون',
    description:' . ',
    price: 14,
    quantity: 35,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 110
  },
       {
    id: 'bee-therapeutic_mixtures-new-4',
    name: 'البابونج مع زهور اللافندر',
    description:' . ',
    price: 11,
    quantity: 45,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 110
  },
       {
    id: 'bee-therapeutic_mixtures-new-5',
    name: 'مزيج الألوفيرا الصبار وزيت جوز الهند',
    description:' . ',
    price: 9,
    quantity: 25,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 100
  },
       {
    id: 'bee-therapeutic_mixtures-new-6',
    name: 'الحبة السوداء حبة البركة مع العسل الطبيعي',
    description:' . ',
    price: 20,
    quantity: 65,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
       {
    id: 'bee-therapeutic_mixtures-new-7',
    name: 'خلطة العسل والبروبوليس الفائقة',
    description:' . ',
    price: 19,
    quantity: 35,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 150
  },
       {
    id: 'bee-therapeutic_mixtures-new-8',
    name: 'كبسولات عكبر النحل (البروبوليس) الطبيعية',
    description:' . ',
    price: 39,
    quantity: 45,
    category: 'therapeutic_mixtures',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 160
  },
       {
    id: 'skin_care-new-1',
    name: 'سيروم الهيالورونيك أسيد المركز',
    description:' . ',
    price: 49,
    quantity: 65,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 140
  },
       {
    id: 'skin_care-new-2',
    name: 'كريم العين',
    description:' . ',
    price: 40,
    quantity: 75,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 130
  },
         {
    id: 'skin_care-new-3',
    name: ' قناع الوجه',
    description:' . ',
    price: 29,
    quantity: 55,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 160
  },
         {
    id: 'skin_care-new-4',
    name: 'واقي الشمس للحماية من أضرار الأشعة فوق البنفسجية',
    description:' . ',
    price: 65,
    quantity: 45,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
         {
    id: 'skin_care-new-5',
    name: 'المرطب لحبس الماء داخل الجلد',
    description:' . ',
    price: 35,
    quantity: 35,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 130
  },
         {
    id: 'skin_care-new-6',
    name: 'السيروم لمعالجة مشاكل الجلد',
    description:' . ',
    price: 59,
    quantity: 35,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 160
  },
         {
    id: 'skin_care-new-7',
    name: 'التونر لضبط درجة الحموضة',
    description:' . ',
    price: 45,
    quantity: 35,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 170
  },
         {
    id: 'skin_care-new-8',
    name: 'الغسول لإزالة الشوائب',
    description:' . ',
    price: 37,
    quantity: 45,
    category: 'skin_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
        {
    id: 'makeup-new-1',
    name: 'البرايمر',
    description:' . ',
    price: 45,
    quantity: 55,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 120
  },
       {
    id: 'makeup-new-2',
    name: 'برايمر العيون',
    description:' . ',
    price: 29,
    quantity: 65,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 170
  },
         {
    id: 'makeup-new-3',
    name: 'أحمر الخدود',
    description:' . ',
    price: 39,
    quantity: 35,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
         {
    id: 'makeup-new-4',
    name: 'الكونتور والبرونزر',
    description:' . ',
    price: 49,
    quantity: 45,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 150
  },
         {
    id: 'makeup-new-5',
    name: 'االهايلايتر',
    description:' . ',
    price: 35,
    quantity: 75,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 140
  },
         {
    id: 'makeup-new-6',
    name: 'االبودرة',
    description:' . ',
    price: 49,
    quantity: 75,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 110
  },
         {
    id: 'makeup-new-7',
    name: 'خافي العيوب',
    description:' . ',
    price: 39,
    quantity: 65,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 160
  },
         {
    id: 'makeup-new-8',
    name: 'كريم الأساس',
    description:' . ',
    price: 49,
    quantity: 45,
    category: 'makeup',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
       {
    id: 'hair_care-new-1',
    name: 'سيروم مغذي للشعر بالأرغان',
    description:' . ',
    price: 49,
    quantity: 65,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 120
  },
       {
    id: 'hair_care-new-2',
    name: 'بلسم الشعر',
    description:' . ',
    price: 25,
    quantity: 45,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 130
  },
         {
    id: 'hair_care-new-3',
    name: 'سيروم الكثافة',
    description:' . ',
    price: 29,
    quantity: 25,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 150
  },
         {
    id: 'hair_care-new-4',
    name: 'سيروم الترطيب واللمعان',
    description:' . ',
    price: 39,
    quantity: 55,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
         {
    id: 'hair_care-new-5',
    name: 'سيروم لعلاج التساقط وتقوية البصيلات',
    description:' . ',
    price: 19,
    quantity: 35,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
         {
    id: 'hair_care-new-6',
    name: 'كريمات تحديد الشعر الكيرلي',
    description:' . ',
    price: 29,
    quantity: 25,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 110
  },
         {
    id: 'hair_care-new-7',
    name: 'الكريمات الواقية من الحرارة',
    description:' . ',
    price: 28,
    quantity: 45,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 150
  },
         {
    id: 'hair_care-new-8',
    name: 'كريمات المعالجة والتغذية',
    description:' . ',
    price: 39,
    quantity: 35,
    category: 'hair_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 130
  },
         {
    id: 'mens_perfumes-new-1',
    name: 'عطر زيرجوف ألكساندريا',
    description:' . ',
    price: 400,
    quantity: 25,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 110
  },
         {
    id: 'mens_perfumes-new-2',
    name: 'عطر توم فورد عود وود',
    description:' . ',
    price: 420,
    quantity: 65,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 170
  },
           {
    id: 'mens_perfumes-new-3',
    name: 'عطر ريف غوش من إيف سان لوران',
    description:' . ',
    price: 350,
    quantity: 45,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.3,
    reviewsCount: 120
  },
           {
    id: 'mens_perfumes-new-4',
    name: 'عطر بايلوت غارمينت من برادا',
    description:' . ',
    price: 150,
    quantity: 25,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 100
  },
           {
    id: 'mens_perfumes-new-5',
    name: 'عطر أومبر نوماد من لويس فويتون',
    description:' . ',
    price: 100,
    quantity: 35,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 160
  },
           {
    id: 'mens_perfumes-new-6',
    name: 'عطر بلو دي شانيل',
    description:' . ',
    price: 450,
    quantity: 65,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 150
  },
           {
    id: 'mens_perfumes-new-7',
    name: 'عطر كريد أفينتس',
    description:' . ',
    price: 250,
    quantity: 55,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
           {
    id: 'mens_perfumes-new-8',
    name: 'عطر سوفاج إلكسير من ديور',
    description:' . ',
    price: 300,
    quantity: 35,
    category: 'mens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
          {
    id: 'womens_perfumes-new-1',
    name: 'عطر توم فورد بلاك أوركيد',
    description:' . ',
    price: 400,
    quantity: 45,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 180
  },
        {
    id: 'womens_perfumes-new-2',
    name: 'عطر جورجيو أرماني سي باسيوني',
    description:' . ',
    price: 200,
    quantity: 45,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 140
  },
          {
    id: 'womens_perfumes-new-3',
    name: 'عطر كارولينا هيريرا جود جيرل',
    description:' . ',
    price: 420,
    quantity: 35,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 165
  },
          {
    id: 'womens_perfumes-new-4',
    name: 'عطر بايسون روج',
    description:' . ',
    price: 370,
    quantity: 65,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 190
  },
          {
    id: 'womens_perfumes-new-5',
    name: 'عطر برادا بارادوكس',
    description:' . ',
    price: 500,
    quantity: 35,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.9,
    reviewsCount: 175
  },
          {
    id: 'womens_perfumes-new-6',
    name: 'عطر إيف سان لوران ليبر إنتنس',
    description:' . ',
    price: 460,
    quantity: 75,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 185
  },
          {
    id: 'womens_perfumes-new-7',
    name: 'عطر ديور جادور',
    description:' . ',
    price: 390,
    quantity: 35,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 170
  },
          {
    id: 'womens_perfumes-new-8',
    name: 'عطر شانيل كوكو مدموزيل',
    description:' . ',
    price: 450,
    quantity: 65,
    category: 'womens_perfumes',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 190
  },
       {
    id: 'mens_care-new-1',
    name: 'زيوت وبلسم اللحية',
    description:' . ',
    price: 40,
    quantity: 75,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 60
  },
       {
    id: 'mens_care-new-2',
    name: 'غسول للجسم',
    description:' . ',
    price: 13,
    quantity: 35,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.0,
    reviewsCount: 10
  },
        {
    id: 'mens_care-new-3',
    name: 'رغوة حلاقة وغسول عناية للرجال',
    description:' . ',
    price: 4,
    quantity: 75,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.1,
    reviewsCount: 60
  },
        {
    id: 'mens_care-new-4',
    name: 'شفرات حلافة من شركة Gillette',
    description:' . ',
    price: 17,
    quantity: 35,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 30
  },
        {
    id: 'mens_care-new-4',
    name: 'كريم لتصفيف الشعر',
    description:' . ',
    price: 23,
    quantity: 45,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 40
  },
        {
    id: 'mens_care-new-6',
    name: 'زيت إنبات اللحية',
    description:' . ',
    price: 19,
    quantity: 65,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 20
  },
        {
    id: 'mens_care-new-7',
    name: 'لوشن ما بعد الحلاقة',
    description:' . ',
    price: 4.99,
    quantity: 65,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 20
  },
        {
    id: 'mens_care-new-8',
    name: 'كريم الحلاقة',
    description:' . ',
    price: 10,
    quantity: 85,
    category: 'mens_care',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.2,
    reviewsCount: 30
  },
      {
    id: 'seasonal_products-new-1',
    name: 'واقي شمس خفيف',
    description:' . ',
    price: 20,
    quantity: 85,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.5,
    reviewsCount: 90
  },
      {
    id: 'seasonal_products-new-2',
    name: 'مقشر لطيف',
    description:' . ',
    price: 20,
    quantity: 45,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 70
  },
        {
    id: 'seasonal_products-new-3',
    name: 'زيت الوجه المغذي',
    description:' . ',
    price: 29,
    quantity: 55,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 70
  },
        {
    id: 'seasonal_products-new-4',
    name: 'مرطب كريمي',
    description:' . ',
    price: 19,
    quantity: 25,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 40
  },
        {
    id: 'seasonal_products-new-5',
    name: 'منظف لطيف',
    description:' . ',
    price: 12,
    quantity: 65,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 80
  },
        {
    id: 'seasonal_products-new-6',
    name: 'بخاخ رذاذ الوجه',
    description:' . ',
    price: 6,
    quantity: 75,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 110
  },
        {
    id: 'seasonal_products-new-7',
    name: 'الجل المرطب المائي',
    description:' . ',
    price: 15,
    quantity: 45,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 80
  },
        {
    id: 'seasonal_products-new-8',
    name: 'سيروم فيتامين سي',
    description:' . ',
    price: 16,
    quantity: 35,
    category: 'seasonal_products',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 70
  },
        {
    id: 'beauty_devices-new-1',
    name: 'جهاز إزالة الشعر بالليزر المنزلي',
    description:' . ',
    price: 50,
    quantity: 35,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 100
  },
       {
    id: 'beauty_devices-new-2',
    name: 'جهاز تقشير الجلد بالكريستال',
    description:' . ',
    price: 60,
    quantity: 25,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.4,
    reviewsCount: 130
  },
       {
    id: 'beauty_devices-new-3',
    name: 'جهاز بخار الوجه الأيوني',
    description:' . ',
    price: 70,
    quantity: 45,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.8,
    reviewsCount: 140
  },
       {
    id: 'beauty_devices-new-4',
    name: 'جهاز تنظيف الوجه السيليكوني',
    description:' . ',
    price: 80,
    quantity: 25,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 150
  },
       {
    id: 'beauty_devices-new-5',
    name: 'جهاز تدليك وشد الوجه بتقنية الضوء',
    description:' . ',
    price: 73,
    quantity: 55,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 120
  },
       {
    id: 'beauty_devices-new-6',
    name: 'جهاز تنظيف البشرة العميق',
    description:' . ',
    price: 85,
    quantity: 65,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 110
  },
       {
    id: 'beauty_devices-new-7',
    name: 'جهاز الهايفو',
    description:' . ',
    price: 75,
    quantity: 65,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.6,
    reviewsCount: 130
  },
       {
    id: 'beauty_devices-new-8',
    name: 'جهاز شد الوجه بالترددات الراديوية',
    description:' . ',
    price: 45,
    quantity: 45,
    category: 'beauty_devices',
    image: 'https://picsum.photos/seed/watch/400/400',
    images: [],
    rating: 4.7,
    reviewsCount: 120
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customerId: 'CUST-1',
    customerName: 'عمار الحلاق',
    items: [{ productId: '1', name: 'IPhone 16 PRO MAX', quantity: 1, price: 1299 }],
    total: 299,
    status: 'delivered',
    date: '2026-03-15'
  },
  {
    id: 'ORD-002',
    customerId: 'CUST-2',
    customerName: 'أحمد السلقيني',
    items: [{ productId: '3', name: 'Samsung S95H OLED Vision AI Smart 4K TV (55")', quantity: 2, price: 4400 }],
    total: 90,
    status: 'processing',
    date: '2026-04-20'
  },
    {
    id: 'ORD-003',
    customerId: 'CUST-3',
    customerName: 'وليد النيفاوي',
    items: [{ productId: '4', name: 'ساعة رياضية ذكية متينة', quantity: 3, price: 747 }],
    total: 70,
    status: 'processing',
    date: '2026-02-10'
  },
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'VEN-1',
    name: 'يحيى شبلوط',
    email: 'yahyashabalout@gmail.com',
    storeName: 'عالم التقنية',
    category: 'إلكترونيات',
    sales: 15400,
    rating: 4.8,
    status: 'active',
    joinDate: '2024-01-10'
  },
  {
    id: 'VEN-2',
    name: 'سالم الحصني',
    email: 'salemalhussne@gmail.com',
    storeName: 'عالم المنزل',
    category: 'كهربائيات',
    sales: 8200,
    rating: 4.5,
    status: 'pending',
    joinDate: '2025-02-15'
  },
    {
    id: 'VEN-3',
    name: 'فائق الدروبي',
    email: 'faekaldroubi@gmail.com',
    storeName: 'منتجات الـ BeePharma',
    category: 'BeePharma',
    sales: 15400,
    rating: 4.8,
    status: 'active',
    joinDate: '2025-09-16'
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-1',
    name: 'وسيم عبدربه',
    email: 'waseemabd@gmail.com',
    totalOrders: 5,
    totalSpent: 1250,
    status: 'active'
  },
  {
    id: 'CUST-2',
    name: 'محمد الصباغ',
    email: 'muhmmadalsabaa@gmail.com',
    totalOrders: 2,
    totalSpent: 180,
    status: 'active'
  },
  {
    id: 'CUST-3',
    name: 'عمر الكيال',
    email: 'omaralkayal@gmail.com',
    totalOrders: 4,
    totalSpent: 1200,
    status: 'active'
  },
];
